config/routes.rb
Rails.application.routes.draw do

  resources :milestones do
    member do
      put :change
    end
  end

  resources :projects

  devise_for :users

    root 'pages#home' #makes the home page the root page

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
    belongs_to :project, :foreign_key => "project_id"
    validates_presence_of :project_id
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :user
    has_many :milestones, dependent: :destroy
    validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
    def after_sign_in_path_for(resource)
        projects_path
    end
    
    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_milestone, only: [:show, :edit, :update, :destroy, :change]

  # GET /milestones
  # GET /milestones.json
  def index
    @notStarted = Milestone.where(state: "to_do")
    @inProgress = Milestone.where(state: "doing")
    @completed = Milestone.where(state: "completed")
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
      session[:return_to] ||= request.referer
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
    #@milestone = Milestone.new(:project_id => params[:project_id])
    #@project = Project.find(params[:project_id])
  end

  # GET /milestones/1/edit
  def edit
      session[:return_to] ||= request.referer
  end

  # POST /milestones
  # POST /milestones.json
  def create
    #@project = Project.find(params[:id])
    #@milestone = @project.milestones.create(milestone_params)

     @milestone = Milestone.new(milestone_params)
    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  def change
    @milestone.update_attributes(state: params[:state])
    respond_to do |format|
    format.html {redirect_to project_path(@milestone.project_id), notice: "Task Update"}
  end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:name, :startDate, :completionDate, :state, :project_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      if current_user
          redirect_to projects_path
      end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
      @notStarted = Milestone.where(state: "to_do")
     #@projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    #@project = Project.new(project_params)
      @project = current_user.projects.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :budget, :ongoingcost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "<i class='fa fa-circle-o-notch'></i>ProManSof".html_safe, root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
         <li><%= link_to 'Projects', projects_path %></li>
        <% end %>
      </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
         <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Managers' Software</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/milestones/_form.html.erb
<%= simple_form_for(@milestone, html: {class: "form-signin"}) do |f| %>
  <p id="notice"><%= f.error_notification %></p>

  <div class="form-inputs">
    <%= f.input :name, label: false, placeholder: "Name" %>
    <%= f.input :startDate, label: false, placeholder: "Start Date", input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>

    <%= f.input :completionDate, label: false, placeholder: "Completion Date",input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>
    <%= f.input :state, label: false, placeholder: "State" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/milestones/_milestone.html.erb
<%= div_for milestone do %>
        <%= h(milestone.name) %>
        <%= h(milestone.startDate) %>
        <%= h(milestone.completionDate) %><br>
        <%= link_to 'Show', milestone %>
        <%= link_to 'Edit', edit_milestone_path(milestone) %>
        <%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% if milestone.state == "to_do" || milestone.state == "completed" %>
        <%= link_to "Mark as Doing", change_milestone_path(milestone, state: "doing"), method::put %>
        <%else%>
        <%= link_to "Mark as To Do", change_milestone_path(milestone, state: "to_do"), method::put %>
        <% end%>
<% end -%>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', project_path(@milestone.project_id) %>

app/views/milestones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Do</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Startdate</th>
      <th>Completiondate</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notStarted.each do |milestone| %>
      <tr>
        <td><%= milestone.name %></td>
        <td><%= milestone.startDate %></td>
        <td><%= milestone.completionDate %></td>
        <td><%= milestone.state %></td>
        <td><%= link_to 'Show', milestone %></td>
        <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
        <td><%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br>

<%= link_to 'New Milestone', new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>



 <p>
  <strong>Name:</strong>
  <%= @milestone.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @milestone.startDate %>
</p>

<p>
  <strong>Completion date:</strong>
  <%= @milestone.completionDate %>
</p>

<p>
  <strong>State:</strong>
  <%= @milestone.state %>
</p>

<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', project_path(@milestone.project_id) %>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>ProManSof</h1>
	<p>Manage your projects and resources with <i class="fa fa-circle-o-notch"></i>ProManSof</p>
	<%= link_to 'Sign up', new_user_registration_path, class: ' btn btn-primary btn-lg' %>
</div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "pm1.jpg", class:"img-responsive" %>
      <div class="caption">
        <h3>Feature 1</h3>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "pm2.jpg", class:"img-responsive" %>
      <div class="caption">
        <h3>Feature 2</h3>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "pm3.jpg", class:"img-responsive" %>
      <div class="caption">
        <h3>Feature 3</h3>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {class: "form-signin"}) do |f| %>
<p id="notice"><%= f.error_notification %></p>

  <div class="form-inputs">
    <%= f.input :title, label:false, placeholder: "Title" %>
    <%= f.input :budget, label:false, placeholder: "Budget" %>
    <%= f.input :ongoingcost, label:false, placeholder: "Ongoing Cost"%>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-block' %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<div class="table-responsive">
<table class="table table-bordered table-hover">
  <thead class="thead-inverse">
    <tr>
      <th>Title</th>
      <th>Budget</th>
      <th>Ongoing Cost</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.budget %></td>
        <td><%= project.ongoingcost %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1 class="text-center">New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
<table class="table table-bordered table-hover">
<tr><td><strong>Title:</strong></td><td><%= @project.title %></td></tr>
<tr><td><strong>Budget:</strong></td><td>$
  <%= @project.budget %>
</td></tr>

<tr><td><strong>Ongoing Cost:</strong></td><td>$
  <%= @project.ongoingcost %>
</td></tr>
</table>
</div>

<h4>Milestones</h4>
<div class="row">
<div id="notStarted" class="col-md-4">
   <h5>Not Started</h5>
    <%= render :partial => @project.milestones.where(state: "to_do") %>
</div>
<div id="inProgress" class="col-md-4">
   <h5>In Progress</h5>
    <%= render :partial => @project.milestones.where(state: "doing")%>
</div>
<div id="completed" class="col-md-4">
   <h5>Completed</h5>
    <%= render :partial => @project.milestones.where(state: "completed") %>
</div>
</div>
<br/>

   <%= simple_form_for([@milestone, Milestone.new], html:{class: "form-horzontal"}, remote:true) do |f|   %>
    <div class="row">
    <div class="col-md-2">
    <%= f.input :name, label: false, placeholder: "Name" %>
        </div>
         <div class="col-md-3">
    <%= f.input :startDate, label: false, placeholder: "Start Date", input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>
 </div>
   <div class="col-md-3">
    <%= f.input :completionDate, label: false, placeholder: "Completion Date",input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>
        </div>
    <div class="col-md-2">
     <%= f.input :state, label: false, placeholder: "State" %></div>
    <%= f.hidden_field :project_id, :value => @project.id%>
    <div class="col-md-2">
    <p><%= f.submit "Add Milestone"%></p></div>

</div>
<% end -%>



<br/>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>